### ISSUE TITLE
error running r2easyR.stem_editor

### ISSUE THREAD

**Issue by Zahraalirezaei** [JPSieg/R2easyR#2]
Dear Team,
I have a problem to optimize stem layouts using r2easyR.stem_editor.
every time I run the command I get the error below:

> r2easyR.stem_editor("example.sto")
Error in if (zoro_n_juction[i - 1]) { : 
  missing value where TRUE/FALSE needed

Could you please help me with this.

Best regards.
Zahra

**Comment by JPSieg** [comment]
Hello Zahra,

Absolutely! I have not run into this problem. Would you mind sending me some files that I will need to reproduce?

I need:

1.) Your R script
2.) Your input text file (csv)
3.) Your output "example.sto"

Please use my PSU email address: jus841@psu.edu

Thank you,

Jacob
________________________________
From: Zahraalirezaei ***@***.***>
Sent: Wednesday, April 14, 2021 1:40 PM
To: JPSieg/R2easyR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JPSieg/R2easyR] error running r2easyR.stem_editor (#2)


Dear Team,
I have a problem to optimize stem layouts using r2easyR.stem_editor.
every time I run the command I get the error below:

r2easyR.stem_editor("example.sto")
Error in if (zoro_n_juction[i - 1]) { :
missing value where TRUE/FALSE needed

Could you please help me with this.

Best regards.
Zahra

**Comment by JPSieg** [comment]
### Hello Zahra,

### You encountered a bug that I did not know existed! Briefly, the stem editor uses different place explicit commands if a stem starts 1 nucleotide from another, called a zero N juction. Thus, the stem editor needs to count how many times this happens. Unfortunately, the old logic tree was only counting after even numbered helices. I have patched the bug but you will need to start a new R session, remove R2easyR, and then reinstall. Code is attached below:

```{r}
#Set up package

remove.packages("R2easyR")
devtools::install_github("JPSieg/R2easyR")

library(R2easyR)

#Read data

df <- read.csv("df.csv")


#Check data

hist(df$Reactivity)

#build palettes

palettes <- r2easyR.palettes()

#Color data

df <- r2easyR.color(df,
                    palettes$PuRd.c,
                    abs_reactivity_threshold = 0.1,
)

#Write R2R inputs

r2easyR.write("df_r2easyr", df, colors = "circles")

#stem place optimisation

r2easyR.stem_editor("df_r2easyr.sto")

```

### This will result in a figure, which will look pretty nice after a little editing in Illustrator. Note, I think a abs_reactivity_threshold = 0.1 filters out some more of the noise in your data, which looks great!

### Does this work for you?

### Thank you,

### Jacob
