### ISSUE TITLE
label "a++" used "++" on a label at the 3' extreme, so that refers to a position that doesn't exist.

### ISSUE THREAD

**Issue by MacMeyer1** [JPSieg/R2easyR#3]
Having issues drawing several hundred structures. It got through about 10 then gave me the error mentioned in the title.

**Comment by JPSieg** [comment]
Hello Mac,

This was an issue that caused the ry.tRNA function to stick an "a++" place explicit command on the 3'-end of a tRNA, which causes the R2R error that you observed. I added some logic to ry.tRNA that prevent this.

It should run after you remove R2easyR and reinstall as described below. Also, please close R/Rstudio and reinstall in a new session to keep anything from going wrong.

```{r}
#Set up package

remove.packages("R2easyR")
devtools::install_github("JPSieg/R2easyR")

library(R2easyR)
```
