### ISSUE TITLE
stem editor error

### ISSUE THREAD

**Issue by AGalanis97** [JPSieg/R2easyR#4]
Hi,

I am unable to run the stem editor as it keeps giving me the following error: 
`Error in if (zoro_n_juction[i - 1]) { : the condition has length > 1
`

The code I am using is the following:
dotbracket <- as.data.frame(unlist(stringr::str_split(string = "((((((.(((((((((((.....((((((.....))))))...)))))))))..))))))))...((((((((((.((((((((((((((((((((((.(((......)))....))))))))))))))....(..((....)))))))))))))))).))))..)",pattern = "")))
colnames(dotbracket) <- "Dotbracket"

nucleotide <- as.data.frame(unlist(stringr::str_split(string="UUAAUUAAGUCAGAUGUGAAAUCCCCGAGCUCAACUUGGGACGUGCAUUUGAAACUGGUUAACUAGAGUGUGUCAGAGGGAGGUAGAAUUCCACGUGUAGCAGUGAAAUGCGUAGAGAUGUGGAGGAAUACCGAUGGCGAAGGCAGCCUCCUGGGAUAACACUGAC",pattern="")))
colnames(nucleotide) <- "Nucleotide"

n_length <- data.frame(N=seq(from=66450,to=66615,by=1))

df_dt <- cbind(n_length,nucleotide,dotbracket)
df_dt <- merge(df_dt,df2,by = "N",all = T)
#### Note: df2 cotains the data per position, let me know if that would be useful.

palettes <- r2easyR.palettes()

df <- r2easyR.color(df_dt,palettes$YlOrRd.c)
r2easyR.write("Example", df, colors = "circles")
r2easyR.stem_editor("Example.sto")

**Comment by JPSieg** [comment]
Hello there,

Thank you for the code to reproduce your problem. The problem is that some parts of R2easyR only works with a "<" or a ">" instead of a "(" or a ")".  This is stupid, I know, but I haven't had time to fix it.

Here is code added to fix what you had.

Thank you for reaching out.

Jacob

```{r}
dotbracket <- as.data.frame(unlist(stringr::str_split(string = "((((((.(((((((((((.....((((((.....))))))...)))))))))..))))))))...((((((((((.((((((((((((((((((((((.(((......)))....))))))))))))))....(..((....)))))))))))))))).))))..)",pattern = "")))
colnames(dotbracket) <- "Dotbracket"

nucleotide <- as.data.frame(unlist(stringr::str_split(string="UUAAUUAAGUCAGAUGUGAAAUCCCCGAGCUCAACUUGGGACGUGCAUUUGAAACUGGUUAACUAGAGUGUGUCAGAGGGAGGUAGAAUUCCACGUGUAGCAGUGAAAUGCGUAGAGAUGUGGAGGAAUACCGAUGGCGAAGGCAGCCUCCUGGGAUAACACUGAC",pattern="")))
colnames(nucleotide) <- "Nucleotide"

n_length <- data.frame(N=seq(from=66450,to=66615,by=1))

df_dt <- cbind(n_length,nucleotide,dotbracket)

####This line models random reactivity data####
df_dt$Reactivity = rgamma(nrow(df_dt), 2, rate = 1)
####                End here               ####

hist(df_dt$Reactivity)
library(R2easyR)

palettes <- r2easyR.palettes()

####These are the lines that fix your code####
df_dt$Dotbracket[which(df_dt$Dotbracket ==  "(")] = "<"
df_dt$Dotbracket[which(df_dt$Dotbracket ==  ")")] = ">"
####                End here              ####

df <- r2easyR.color(df_dt,palettes$YlOrRd.c)
r2easyR.write("Example", df, colors = "circles")
r2easyR.stem_editor("Example.sto")
```
[Example.pdf](https://github.com/JPSieg/R2easyR/files/12322247/Example.pdf)
